### ISSUE TITLE
Plugin zip cache: Try to download latest release before cloning

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/awesome-plugins-backend#10]
We are giving community a recommended way of creating a plugin, with [this template](https://github.com/cheshire-cat-ai/plugin-template) that handles releases creating a ready made zip to download via Github public api.

Since method [`Endpoints.download_plugin_zip`](https://github.com/cheshire-cat-ai/awesome-plugins-backend/blob/ada44ff722696aadea8c8cf945e1166da357aef4/endpoints.py#L181) is already dealing with the creation of the zip, covering all non-template use cases, I propose to:

- take away this logic from core and rely on this service, to avoid duplicates
- check in `Endpoints.download_plugin_zip` if there is a release zip via Github public api (as done [here](https://github.com/cheshire-cat-ai/core/blob/fe03d5a5fd8109972db720c416571bb02ee95823/core/cat/routes/plugins.py#L100))
- If no release is available,  proceeds to clone the repo and create the zip as it already does

Maybe @valentimarco is interested at working on this (also @nicola-corbellini )

**Comment by valentimarco** [comment]
Ye, i am interested!

**Comment by pieroit** [comment]
@valentimarco so the sequence would be this for function `Endpoints.download_plugin_zip`:
1 - check for the latest release via Github public api (the code you already wrote in core)
2 - if no release is available, go on cloning adn cleaning the code (what the actual function does)

Thanks! Let me know if you need clarification

**Comment by EugenioPetulla** [comment]
I'm glad that someone is collaborating on this repository! Let me know if you have any needs, and I'll be super-happy to assist you.

I'm looking forward to reading your pull requests!

**Comment by valentimarco** [comment]
@EugenioPetulla i have a problem with the build right now: when i try to download a zip that is in the cache, python throws a PermissionError
Can we discuss on discord?
